name: ros2-cli
version: jazzy
summary: Command line interface tools for ROS2
description: |
  Snap for ROS 2 command line interface tools [1] included with a standard install of any ROS 2 distro.
  
  Note: This is a beta release, if you encounter any bugs or limitations, please do report it [2].

  The Snap does not support roslaunch, rospkg, rosrun and custom ROS messages as these require access to the host filesystem.
  The ros2-cheat-sheet [3] provides examples for commands and their verbs.

  Installation Instructions:

  * Install ros2cli from a terminal,
  `snap install ros2-cli --channel=jazzy/beta`

  * Test your installation,
  `ros2-cli.ros2 --help`

  [1] https://github.com/ros2/ros2cli
  [2] https://github.com/ubuntu-robotics/ros2cli-snap/issues
  [3] https://github.com/ubuntu-robotics/ros2_cheats_sheet/blob/master/cli/cli_cheats_sheet.pdf

issues: https://github.com/ubuntu-robotics/ros2cli-snap/issues
source-code: https://github.com/ubuntu-robotics/ros2cli-snap
license: Apache-2.0

grade: devel
confinement: strict
base: core24

apps:
  ros2:
    command: opt/ros/snap/bin/ros2
    plugs: [home, network, network-bind]
    environment:
      # Add blas and lapack to library path, needed for numpy dependency
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack"
      # Disable FastDDS shared-memory
      FASTRTPS_DEFAULT_PROFILES_FILE: "${SNAP}/usr/share/fastdds_no_shared_memory.xml"
    extensions: [ros2-jazzy-ros-base]

parts:
  # fastdds-no-shared-memory:
  #   plugin: dump
  #   source: snap/local/
  #   organize:
  #     'fastdds_no_shared_memory.xml': usr/share/
# prevent module error using 'distutils', removed from python 3.12
  python-deps:
    plugin: python
    source: .
    python-packages:
      - setuptools

  ros2cli:
    plugin: colcon
    source: https://github.com/ros2/ros2cli.git
    source-branch: jazzy
    override-build: |
      sed -i '6i \\import warnings; warnings.filterwarnings("ignore", category=DeprecationWarning)' /usr/bin/rosdep
      snapcraftctl build
    colcon-packages-ignore:
      - ros2pkg
      - ros2run
      - ros2launch
    build-packages:
      - ros-jazzy-rosidl-adapter

  jazzy-desktop-libamdhip-exec-stack:
    # https://github.com/ROCm/clr/issues/22
    after: [ros2cli]
    plugin: nil
    build-packages: [execstack]
    override-prime: |
      # try remove execstack on libamdhip
      amdlib="$(readlink -f usr/lib/x86_64-linux-gnu/libamdhip64.so.5)"
      if [ -f $amdlib ]; then
        execstack -c $amdlib
      fi
