name: ros2-cli
version: humble
summary: Command line interface tools for ROS2
description: |
  Snap for ROS 2 command line interface tools [1] included with a standard install of any ROS 2 distro.
  
  Note: This is a beta release, if you encounter any bugs or limitations, please do report it [2].

  The Snap does not support roslaunch, rospkg, rosrun and custom ROS messages as these require access to the host filesystem.
  The ros2-cheat-sheet [3] provides examples for commands and their verbs.

  Installation Instructions:

  * Install ros2cli from a terminal,
  `snap install ros2-cli --channel=humble/beta`

  * Test your installation,
  `ros2-cli.ros2 --help`

  [1] https://github.com/ros2/ros2cli
  [2] https://github.com/ubuntu-robotics/ros2cli-snap/issues
  [3] https://github.com/ubuntu-robotics/ros2_cheats_sheet/blob/master/cli/cli_cheats_sheet.pdf

issues: https://github.com/ubuntu-robotics/ros2cli-snap/issues
source-code: https://github.com/ubuntu-robotics/ros2cli-snap
license: Apache-2.0

grade: devel
confinement: strict
base: core22

apps:
  ros2:
    command: opt/ros/snap/bin/ros2
    plugs: [home, network, network-bind]
    environment:
      # Add blas and lapack to library path, needed for numpy dependency
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
      # Disable FastDDS shared-memory
      FASTRTPS_DEFAULT_PROFILES_FILE: "${SNAP}/usr/share/fastdds_no_shared_memory.xml"
    extensions: [ros2-humble]

parts:
  fastdds-no-shared-memory:
    plugin: dump
    source: snap/local/
    organize:
      'fastdds_no_shared_memory.xml': usr/share/

  ros2cli:
    plugin: colcon
    source: https://github.com/ros2/ros2cli.git
    source-branch: humble
    colcon-packages-ignore:
      - ros2pkg
      - ros2run
      - ros2launch
    build-packages:
      - ros-humble-rosidl-adapter
    stage-packages:
      - ros-humble-rosidl-adapter
      # msgs
      - ros-humble-ackermann-msgs
      - ros-humble-action-msgs-dbgsym
      - ros-humble-action-msgs
      - ros-humble-actionlib-msgs-dbgsym
      - ros-humble-actionlib-msgs
      - ros-humble-automotive-autonomy-msgs
      - ros-humble-automotive-navigation-msgs-dbgsym
      - ros-humble-automotive-navigation-msgs
      - ros-humble-automotive-platform-msgs-dbgsym
      - ros-humble-automotive-platform-msgs
      - ros-humble-autoware-auto-msgs-dbgsym
      - ros-humble-autoware-auto-msgs
      - ros-humble-can-msgs-dbgsym
      - ros-humble-can-msgs
      - ros-humble-cartographer-ros-msgs-dbgsym
      - ros-humble-cartographer-ros-msgs
      - ros-humble-cascade-lifecycle-msgs-dbgsym
      - ros-humble-cascade-lifecycle-msgs
      - ros-humble-control-msgs-dbgsym
      - ros-humble-control-msgs
      - ros-humble-controller-manager-msgs-dbgsym
      - ros-humble-controller-manager-msgs
      - ros-humble-depthai-ros-msgs-dbgsym
      - ros-humble-depthai-ros-msgs
      - ros-humble-diagnostic-msgs-dbgsym
      - ros-humble-diagnostic-msgs
      - ros-humble-dwb-msgs-dbgsym
      - ros-humble-dwb-msgs
      - ros-humble-dynamixel-workbench-msgs-dbgsym
      - ros-humble-dynamixel-workbench-msgs
      - ros-humble-four-wheel-steering-msgs-dbgsym
      - ros-humble-four-wheel-steering-msgs
      - ros-humble-foxglove-msgs-dbgsym
      - ros-humble-foxglove-msgs
      - ros-humble-gazebo-msgs-dbgsym
      - ros-humble-gazebo-msgs
      - ros-humble-geographic-msgs-dbgsym
      - ros-humble-geographic-msgs
      - ros-humble-geometry-msgs-dbgsym
      - ros-humble-geometry-msgs
      - ros-humble-gps-msgs-dbgsym
      - ros-humble-gps-msgs
      - ros-humble-graph-msgs-dbgsym
      - ros-humble-graph-msgs
      - ros-humble-grasping-msgs-dbgsym
      - ros-humble-grasping-msgs
      - ros-humble-grbl-msgs-dbgsym
      - ros-humble-grbl-msgs
      - ros-humble-grid-map-msgs-dbgsym
      - ros-humble-grid-map-msgs
      - ros-humble-irobot-create-msgs-dbgsym
      - ros-humble-irobot-create-msgs
      - ros-humble-leo-msgs-dbgsym
      - ros-humble-leo-msgs
      - ros-humble-lgsvl-msgs-dbgsym
      - ros-humble-lgsvl-msgs
      - ros-humble-lifecycle-msgs-dbgsym
      - ros-humble-lifecycle-msgs
      - ros-humble-map-msgs-dbgsym
      - ros-humble-map-msgs
      - ros-humble-marti-can-msgs-dbgsym
      - ros-humble-marti-can-msgs
      - ros-humble-marti-common-msgs-dbgsym
      - ros-humble-marti-common-msgs
      - ros-humble-marti-dbw-msgs-dbgsym
      - ros-humble-marti-dbw-msgs
      - ros-humble-marti-introspection-msgs-dbgsym
      - ros-humble-marti-introspection-msgs
      - ros-humble-marti-nav-msgs-dbgsym
      - ros-humble-marti-nav-msgs
      - ros-humble-marti-perception-msgs-dbgsym
      - ros-humble-marti-perception-msgs
      - ros-humble-marti-sensor-msgs-dbgsym
      - ros-humble-marti-sensor-msgs
      - ros-humble-marti-status-msgs-dbgsym
      - ros-humble-marti-status-msgs
      - ros-humble-marti-visualization-msgs-dbgsym
      - ros-humble-marti-visualization-msgs
      - ros-humble-marvelmind-ros2-msgs-dbgsym
      - ros-humble-marvelmind-ros2-msgs
      - ros-humble-mavros-msgs-dbgsym
      - ros-humble-mavros-msgs
      - ros-humble-micro-ros-diagnostic-msgs-dbgsym
      - ros-humble-micro-ros-diagnostic-msgs
      - ros-humble-micro-ros-msgs-dbgsym
      - ros-humble-micro-ros-msgs
      - ros-humble-microstrain-inertial-msgs-dbgsym
      - ros-humble-microstrain-inertial-msgs
      - ros-humble-moveit-msgs-dbgsym
      - ros-humble-moveit-msgs
      - ros-humble-mrpt-msgs-dbgsym
      - ros-humble-mrpt-msgs
      - ros-humble-nao-command-msgs-dbgsym
      - ros-humble-nao-command-msgs
      - ros-humble-nao-sensor-msgs-dbgsym
      - ros-humble-nao-sensor-msgs
      - ros-humble-nav-2d-msgs-dbgsym
      - ros-humble-nav-2d-msgs
      - ros-humble-nav-msgs-dbgsym
      - ros-humble-nav-msgs
      - ros-humble-nav2-msgs-dbgsym
      - ros-humble-nav2-msgs
      - ros-humble-nmea-msgs-dbgsym
      - ros-humble-nmea-msgs
      - ros-humble-novatel-gps-msgs-dbgsym
      - ros-humble-novatel-gps-msgs
      - ros-humble-object-recognition-msgs-dbgsym
      - ros-humble-object-recognition-msgs
      - ros-humble-octomap-msgs-dbgsym
      - ros-humble-octomap-msgs
      - ros-humble-ouster-msgs-dbgsym
      - ros-humble-ouster-msgs
      - ros-humble-pal-statistics-msgs-dbgsym
      - ros-humble-pal-statistics-msgs
      - ros-humble-pcl-msgs-dbgsym
      - ros-humble-pcl-msgs
      - ros-humble-pendulum-msgs-dbgsym
      - ros-humble-pendulum-msgs
      - ros-humble-phidgets-msgs-dbgsym
      - ros-humble-phidgets-msgs
      - ros-humble-plansys2-msgs-dbgsym
      - ros-humble-plansys2-msgs
      - ros-humble-plotjuggler-msgs-dbgsym
      - ros-humble-plotjuggler-msgs
      - ros-humble-radar-msgs-dbgsym
      - ros-humble-radar-msgs
      - ros-humble-rc-common-msgs-dbgsym
      - ros-humble-rc-common-msgs
      - ros-humble-rc-reason-msgs-dbgsym
      - ros-humble-rc-reason-msgs
      - ros-humble-rclpy-message-converter-msgs-dbgsym
      - ros-humble-rclpy-message-converter-msgs
      - ros-humble-rcss3d-agent-msgs-dbgsym
      - ros-humble-rcss3d-agent-msgs
      - ros-humble-realsense2-camera-msgs-dbgsym
      - ros-humble-realsense2-camera-msgs
      - ros-humble-rmf-api-msgs
      - ros-humble-rmf-building-map-msgs-dbgsym
      - ros-humble-rmf-building-map-msgs
      - ros-humble-rmf-charger-msgs-dbgsym
      - ros-humble-rmf-charger-msgs
      - ros-humble-rmf-dispenser-msgs-dbgsym
      - ros-humble-rmf-dispenser-msgs
      - ros-humble-rmf-door-msgs-dbgsym
      - ros-humble-rmf-door-msgs
      - ros-humble-rmf-fleet-msgs-dbgsym
      - ros-humble-rmf-fleet-msgs
      - ros-humble-rmf-ingestor-msgs-dbgsym
      - ros-humble-rmf-ingestor-msgs
      - ros-humble-rmf-lift-msgs-dbgsym
      - ros-humble-rmf-lift-msgs
      - ros-humble-rmf-obstacle-msgs-dbgsym
      - ros-humble-rmf-obstacle-msgs
      - ros-humble-rmf-scheduler-msgs-dbgsym
      - ros-humble-rmf-scheduler-msgs
      - ros-humble-rmf-site-map-msgs-dbgsym
      - ros-humble-rmf-site-map-msgs
      - ros-humble-rmf-task-msgs-dbgsym
      - ros-humble-rmf-task-msgs
      - ros-humble-rmf-traffic-msgs-dbgsym
      - ros-humble-rmf-traffic-msgs
      - ros-humble-rmf-visualization-msgs-dbgsym
      - ros-humble-rmf-visualization-msgs
      - ros-humble-rmf-workcell-msgs-dbgsym
      - ros-humble-rmf-workcell-msgs
      - ros-humble-robot-calibration-msgs-dbgsym
      - ros-humble-robot-calibration-msgs
      - ros-humble-robot-controllers-msgs-dbgsym
      - ros-humble-robot-controllers-msgs
      - ros-humble-rosapi-msgs-dbgsym
      - ros-humble-rosapi-msgs
      - ros-humble-rosbridge-msgs-dbgsym
      - ros-humble-rosbridge-msgs
      - ros-humble-rosbridge-test-msgs-dbgsym
      - ros-humble-rosbridge-test-msgs
      - ros-humble-rosgraph-msgs-dbgsym
      - ros-humble-rosgraph-msgs
      - ros-humble-rviz-2d-overlay-msgs-dbgsym
      - ros-humble-rviz-2d-overlay-msgs
      - ros-humble-sensor-msgs-dbgsym
      - ros-humble-sensor-msgs-py
      - ros-humble-sensor-msgs
      - ros-humble-shape-msgs-dbgsym
      - ros-humble-shape-msgs
      - ros-humble-smacc2-msgs-dbgsym
      - ros-humble-smacc2-msgs
      - ros-humble-soccer-object-msgs-dbgsym
      - ros-humble-soccer-object-msgs
      - ros-humble-soccer-vision-2d-msgs-dbgsym
      - ros-humble-soccer-vision-2d-msgs
      - ros-humble-soccer-vision-3d-msgs-dbgsym
      - ros-humble-soccer-vision-3d-msgs
      - ros-humble-soccer-vision-attribute-msgs-dbgsym
      - ros-humble-soccer-vision-attribute-msgs
      - ros-humble-statistics-msgs-dbgsym
      - ros-humble-statistics-msgs
      - ros-humble-std-msgs-dbgsym
      - ros-humble-std-msgs
      - ros-humble-stereo-msgs-dbgsym
      - ros-humble-stereo-msgs
      - ros-humble-stubborn-buddies-msgs-dbgsym
      - ros-humble-stubborn-buddies-msgs
      - ros-humble-system-modes-msgs-dbgsym
      - ros-humble-system-modes-msgs
      - ros-humble-teleop-tools-msgs-dbgsym
      - ros-humble-teleop-tools-msgs
      - ros-humble-test-msgs-dbgsym
      - ros-humble-test-msgs
      - ros-humble-tf2-geometry-msgs
      - ros-humble-tf2-msgs-dbgsym
      - ros-humble-tf2-msgs
      - ros-humble-tf2-sensor-msgs
      - ros-humble-trajectory-msgs-dbgsym
      - ros-humble-trajectory-msgs
      - ros-humble-turtlebot3-msgs-dbgsym
      - ros-humble-turtlebot3-msgs
      - ros-humble-ublox-msgs-dbgsym
      - ros-humble-ublox-msgs
      - ros-humble-ublox-ubx-msgs-dbgsym
      - ros-humble-ublox-ubx-msgs
      - ros-humble-udp-msgs-dbgsym
      - ros-humble-udp-msgs
      - ros-humble-unique-identifier-msgs-dbgsym
      - ros-humble-unique-identifier-msgs
      - ros-humble-ur-dashboard-msgs-dbgsym
      - ros-humble-ur-dashboard-msgs
      - ros-humble-ur-msgs-dbgsym
      - ros-humble-ur-msgs
      - ros-humble-urg-node-msgs-dbgsym
      - ros-humble-urg-node-msgs
      - ros-humble-velodyne-msgs-dbgsym
      - ros-humble-velodyne-msgs
      - ros-humble-vision-msgs-dbgsym
      - ros-humble-vision-msgs-layers-dbgsym
      - ros-humble-vision-msgs-layers
      - ros-humble-vision-msgs
      - ros-humble-visualization-msgs-dbgsym
      - ros-humble-visualization-msgs
      - ros-humble-webots-ros2-msgs-dbgsym
      - ros-humble-webots-ros2-msgs
      - ros-humble-wiimote-msgs-dbgsym
      - ros-humble-wiimote-msgs
      # srvs
      - ros-humble-cob-srvs
      - ros-humble-cob-srvs-dbgsym
      - ros-humble-mocap4r2-marker-viz-srvs
      - ros-humble-mocap4r2-marker-viz-srvs-dbgsym
      - ros-humble-qb-softhand-industry-srvs
      - ros-humble-qb-softhand-industry-srvs-dbgsym
      - ros-humble-std-srvs
      - ros-humble-std-srvs-dbgsym
      # Additional DDS vendors
      - ros-humble-rmw-cyclonedds-cpp
      - ros-humble-rmw-fastrtps-cpp
      ## Commenting out the tier2 dds implementation for now. To add only in the future if required.
      ## When added they return the following runtime warning:
      ## [connext_cmake_module] Warning: The location at which Connext was found
      ## when the workspace was built [[/opt/rti.com/rti_connext_dds-5.3.1]] does not point to a valid directory,
      ## and the NDDSHOME environment variable has not been set. Support for Connext will not be available.
      #--ros-humble-rmw-connext-cpp
      #--ros-humble-rmw-gurumdds-cpp

  openai:
    plugin: python
    source: .
    python-packages: [openai]

  ros2ai:
    plugin: colcon
    source: https://github.com/fujitatomoya/ros2ai.git
    source-branch: rolling
    # Avoid pulling ros2cli while it's served by the part above
    override-build: |
      sed -i "\|<exec_depend>ros2cli</exec_depend>|d" "${SNAPCRAFT_PART_SRC}/package.xml"
      craftctl default
    stage:
      - -opt/ros/snap/local_setup.sh
      - -opt/ros/snap/setup.bash
      - -opt/ros/snap/setup.ps1
      - -opt/ros/snap/setup.sh
      - -opt/ros/snap/setup.zsh
