name: ros2-cli
base: core20
version: foxy
summary: Command line interface tools for ROS2
description: |
  Snap for ROS 2 command line interface tools [1] included with a standard install of any ROS 2 distro.

  **Note**: This is a beta release, do expect bugs and limitations. If you encounter any, please do report i>

  The Snap lacks support for tools like roslaunch, rospkg, and rosrun, as these require access to the user's>
  Additionally, only ROS released messages are supported, not custom ones, for the same reason.

  The ros2-cheat-sheet [3] provides examples for commands and their verbs.

  Installation Instructions:

  * Install ros2cli from a terminal,
  `snap install ros2-cli --channel=foxy/beta`

  * Test your installation,
  `ros2-cli.ros2 --help`

  [1] https://github.com/ros2/ros2cli
  [2] https://github.com/ubuntu-robotics/ros2cli-snap/issues
  [3] https://github.com/ubuntu-robotics/ros2_cheats_sheet/blob/master/cli/cli_cheats_sheet.pdf


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict #strict # use 'strict' once you have the right plugs and slots

apps:
  ros2:
    command: opt/ros/snap/bin/ros2
    plugs: [network, network-bind]
    environment:
      # Add blas and lapack to library path, needed for numpy dependency
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
      # Disable FastDDS shared-memory
      FASTRTPS_DEFAULT_PROFILES_FILE: "${SNAP}/usr/share/fastdds_no_shared_memory.xml"
    extensions: [ros2-foxy]

parts:
  fastdds-no-shared-memory:
    plugin: dump
    source: snap/local/
    organize:
      'fastdds_no_shared_memory.xml': usr/share/

  ros2cli:
    plugin: colcon
    source: https://github.com/ros2/ros2cli.git
    source-branch: foxy
    colcon-packages-ignore:
      - ros2pkg
      - ros2run
      - ros2launch
      # Ignoring ros2 doctor. It is using python-ifcfg and having problems
      # in retrieving ifconfig flags within snap. Leaving it for now since
      # this implementation is deprecated in ROS Humble
      - ros2doctor
    stage-packages:
      # No custom message is going to be support for now
      - ros-foxy-ackermann-msgs
      - ros-foxy-action-msgs
      - ros-foxy-actionlib-msgs
      - ros-foxy-astuff-sensor-msgs
      - ros-foxy-automotive-autonomy-msgs
      - ros-foxy-automotive-navigation-msgs
      - ros-foxy-automotive-platform-msgs
      - ros-foxy-autoware-auto-msgs
      - ros-foxy-can-msgs
      - ros-foxy-carla-msgs
      - ros-foxy-cartographer-ros-msgs
      - ros-foxy-cascade-lifecycle-msgs
      - ros-foxy-clober-msgs
      - ros-foxy-clpe-ros-msgs
      - ros-foxy-control-msgs
      - ros-foxy-controller-manager-msgs
      - ros-foxy-dataspeed-dbw-msgs
      - ros-foxy-dataspeed-ulc-msgs
      - ros-foxy-dbw-fca-msgs
      - ros-foxy-dbw-ford-msgs
      - ros-foxy-dbw-polaris-msgs
      - ros-foxy-delphi-esr-msgs
      - ros-foxy-delphi-mrr-msgs
      - ros-foxy-delphi-srr-msgs
      - ros-foxy-depthai-ros-msgs
      - ros-foxy-derived-object-msgs
      - ros-foxy-diagnostic-msgs
      - ros-foxy-dwb-msgs
      - ros-foxy-four-wheel-steering-msgs
      - ros-foxy-foxglove-msgs
      - ros-foxy-gazebo-msgs
      - ros-foxy-geographic-msgs
      - ros-foxy-geometry-msgs
      - ros-foxy-gps-msgs
      - ros-foxy-graph-msgs
      - ros-foxy-grasping-msgs
      - ros-foxy-grbl-msgs
      - ros-foxy-husky-msgs
      - ros-foxy-ibeo-msgs
      - ros-foxy-kartech-linear-actuator-msgs
      - ros-foxy-leo-msgs
      - ros-foxy-lgsvl-msgs
      - ros-foxy-lifecycle-msgs
      - ros-foxy-map-msgs
      - ros-foxy-marti-can-msgs
      - ros-foxy-marti-common-msgs
      - ros-foxy-marti-dbw-msgs
      - ros-foxy-marti-introspection-msgs
      - ros-foxy-marti-nav-msgs
      - ros-foxy-marti-perception-msgs
      - ros-foxy-marti-sensor-msgs
      - ros-foxy-marti-status-msgs
      - ros-foxy-marti-visualization-msgs
      - ros-foxy-mavros-msgs
      - ros-foxy-micro-ros-diagnostic-msgs
      - ros-foxy-micro-ros-msgs
      - ros-foxy-microstrain-inertial-msgs
      - ros-foxy-mobileye-560-660-msgs
      - ros-foxy-mocap-msgs
      - ros-foxy-move-base-msgs
      - ros-foxy-moveit-msgs
      - ros-foxy-mrpt-msgs
      - ros-foxy-nav-2d-msgs
      - ros-foxy-nav-msgs
      - ros-foxy-nav2-msgs
      - ros-foxy-neobotix-usboard-msgs
      - ros-foxy-nmea-msgs
      - ros-foxy-novatel-gps-msgs
      - ros-foxy-object-recognition-msgs
      - ros-foxy-octomap-msgs
      - ros-foxy-ouster-msgs
      - ros-foxy-pacmod-msgs
      - ros-foxy-pcl-msgs
      - ros-foxy-pendulum-msgs
      - ros-foxy-phidgets-msgs
      - ros-foxy-plansys2-msgs
      - ros-foxy-radar-msgs
      - ros-foxy-raptor-dbw-msgs
      - ros-foxy-raptor-pdu-msgs
      - ros-foxy-raspimouse-msgs
      - ros-foxy-rc-common-msgs
      - ros-foxy-rc-reason-msgs
      - ros-foxy-realsense-msgs
      - ros-foxy-realsense2-camera-msgs
      - ros-foxy-rmf-building-map-msgs
      - ros-foxy-rmf-charger-msgs
      - ros-foxy-rmf-dispenser-msgs
      - ros-foxy-rmf-door-msgs
      - ros-foxy-rmf-fleet-msgs
      - ros-foxy-rmf-ingestor-msgs
      - ros-foxy-rmf-lift-msgs
      - ros-foxy-rmf-task-msgs
      - ros-foxy-rmf-traffic-msgs
      - ros-foxy-rmf-visualization-msgs
      - ros-foxy-rmf-workcell-msgs
      - ros-foxy-robot-controllers-msgs
      - ros-foxy-rosapi-msgs
      - ros-foxy-rosbridge-msgs
      - ros-foxy-rosbridge-test-msgs
      - ros-foxy-rosgraph-msgs
      - ros-foxy-rover-msgs
      - ros-foxy-sensor-msgs
      - ros-foxy-shape-msgs
      - ros-foxy-smacc2-msgs
      - ros-foxy-soccer-object-msgs
      - ros-foxy-statistics-msgs
      - ros-foxy-std-msgs
      - ros-foxy-stereo-msgs
      - ros-foxy-stubborn-buddies-msgs
      - ros-foxy-system-modes-msgs
      - ros-foxy-teleop-tools-msgs
      - ros-foxy-test-msgs
      - ros-foxy-tf2-geometry-msgs
      - ros-foxy-tf2-msgs
      - ros-foxy-tf2-sensor-msgs
      - ros-foxy-trajectory-msgs
      - ros-foxy-turtlebot3-msgs
      - ros-foxy-ublox-msgs
      - ros-foxy-udp-msgs
      - ros-foxy-unique-identifier-msgs
      - ros-foxy-ur-msgs
      - ros-foxy-urg-node-msgs
      - ros-foxy-velodyne-msgs
      - ros-foxy-vision-msgs
      - ros-foxy-visualization-msgs
      - ros-foxy-vrxperience-msgs
      - ros-foxy-webots-ros2-msgs
      - ros-foxy-wiimote-msgs
      # Additional DDS vendors
      - ros-foxy-rmw-cyclonedds-cpp
      - ros-foxy-rmw-fastrtps-cpp
      ## Commenting out the tier2 dds implementation for now. To add only in the future if required.
      ## When added they return the following runtime warning:
      ## [connext_cmake_module] Warning: The location at which Connext was found 
      ## when the workspace was built [[/opt/rti.com/rti_connext_dds-5.3.1]] does not point to a valid directory,
      ## and the NDDSHOME environment variable has not been set. Support for Connext will not be available.
      #- ros-foxy-rmw-connext-cpp
      #- ros-foxy-rmw-gurumdds-cpp
