name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  humble:
    permissions: {}
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      git-ref: "humble"
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "medium", "noble"]]'
      snapcraft-enable-experimental-extensions: true
      snap-track: humble
      snap-test-script: |
        #!/bin/bash

        ros2-cli.ros2 --help
  jazzy:
    permissions: {}
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      git-ref: "jazzy"
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "large", "noble"]]'
      snapcraft-enable-experimental-extensions: true
      snap-track: jazzy
      snap-test-script: |
        #!/bin/bash

        ros2-cli.ros2 --help
