name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  humble:
    uses: ./.github/workflows/snap.yaml
    with:
      git-ref: "humble"
  jazzy:
    uses: ./.github/workflows/snap.yaml
    with:
      git-ref: "jazzy"
