name: snap
on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "large", "noble"]]'
      snapcraft-enable-experimental-extensions: true
      snap-track: humble
      snap-test-script: |
        #!/bin/bash

        ros2 --help
