name: snap
on:
  push:
    tags:
      - 'humble/*'
    branches:
      - humble
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches:
      - humble
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "medium", "noble"]]'
      snapcraft-enable-experimental-extensions: true
      snap-track: humble
      snap-test-script: |
        #!/bin/bash

        ros2-cli.ros2 --help
