name: snap
on:
  push:
    tags:
      - 'jazzy/*'
    branches:
      - jazzy
    paths-ignore:
      - .github/worflows/promote.yaml
      - README.md
      - .gitignore
  pull_request:
    branches:
      - jazzy
    paths-ignore:
      - .github/worflows/promote.yaml
      - README.md
      - .gitignore
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "large", "noble"]]'
      snapcraft-enable-experimental-extensions: true
      snap-track: jazzy
      snap-test-script: |
        #!/bin/bash

        ros2-cli.ros2 --help
